create table physical_report (
    id int auto_increment comment '自增主键',
    id_lewalk varchar(100) default NULL comment '乐动力id',
    id_splan varchar(100) default NULL comment 'S计划id',
    id_wechat varchar(100) default NULL comment '微信id',
    id_browser varchar(100) default NULL comment '浏览器id',
    name varchar(100) default '' comment '姓名',
    avatar text default '' comment '头像',
    gender varchar(100) default '' comment '性别',
    phone varchar(100) default '' comment '联系方式',
    age int default 0 comment '年龄',
    height float default 0 comment '身高',
    weight float default 0 comment '体重',
    work float default 0 comment '工作状态',
    sport float default 0 comment '运动习惯',
    up_fat float default 0 comment '体脂率上限',
    down_fat float default 0 comment '体脂率下限',
    wrist float default 0 comment '手腕围度',
    aerobic_heart int default 0 comment '台阶心率',
    anaerobic_heart int default 0 comment '高抬腿心率',
    push_ups int default 0 comment '俯卧撑次数',
    volume_abdomen int default 0 comment '卷腹次数',
    squatting int default 0 comment '深蹲次数',
    status int default 1 comment '0:无效 1:有效',
    update_time datetime default current_timestamp on update current_timestamp comment '更新时间',
    create_time datetime default current_timestamp comment '创建时间',
    primary key (id),
    unique uni_id_lewalk (id_lewalk),
    unique uni_id_splan (id_splan),
    unique uni_id_wechat (id_wechat),
    unique uni_id_browser (id_browser)
);
